version: '3'
services:
  geometry-client:
    container_name: geometry-client-c
    image: geometry-client-i
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - geometry-service-java
    networks:
      - geometry-service
    environment:
      - GEOMETRY_SERVICE_HOST=geometry-service-java:8980

  geometry-service-java:
    container_name: geometry-service-java-c
    image: geometry-service-java-i
    ports:
      - "8980:8980"
    networks:
      - geometry-service

networks:
  geometry-service: {}
