apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: geometry-operators
  labels:
    app: geometry-service
spec:
  selector:
    matchLabels:
      app: geometry-service
  replicas: 3
  template:
    metadata:
      labels:
        app: geometry-service
    spec:
      containers:
      - name: geometry-service
        image: echoparklabs/geometry-service-java:8-jre-alpine
        ports:
        - name: geometry-port
          containerPort: 8980
---
apiVersion: v1
kind: Service
metadata:
  name: geometry-operators
spec:
  selector:
    app: geometry-service
  ports:
  - port: 8980
    targetPort: geometry-port
