apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  replicas: 1
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: go-client:latest
        imagePullPolicy: Never
        env:
        - name: GEOMETRY_SERVICE_TARGET
          value: "geometry-operators:8980"
        ports:
        - name: geom-port
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: go-api
spec:
  type: NodePort
  selector:
    app: go-api
  ports:
  - port: 9090
    targetPort: geom-port
